services:
  - type: web
    name: smart-water-backend
    env: node
    plan: free
    buildCommand: npm ci && npm run build && python3 -m pip install -r requirements.txt
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PYTHON_BIN
        value: python3
      - key: MQTT_ENABLED
        value: "false"
      - key: MONGO_URI
        sync: false
      - key: JWT_ACCESS_SECRET
        sync: false
      - key: JWT_REFRESH_SECRET
        sync: false
      - key: GOOGLE_WEB_CLIENT_ID
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: CORS_ORIGINS
        sync: false
      - key: MQTT_URL
        sync: false
      - key: MQTT_USERNAME
        sync: false
      - key: MQTT_PASSWORD
        sync: false
